sudo: required
# docker run -it -v $(pwd):/app ruby:2.3 sh
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_de3fbf7e1c36_key -iv $encrypted_de3fbf7e1c36_iv -in service-account.json.enc -out service-account.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project rcrts-1536824246188
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials rcrts-multi-cluster
  - docker build -t johnhigginsavila/middleware-api-test -f Dockerfile.dev .
script:
  - docker run johnhigginsavila/middleware-api-test npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master