apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: middleware-api
  template:
    metadata:
      labels:
        component: middleware-api
    spec:
      containers:
        - name: middleware-api
          image: johnhigginsavila/middleware-api
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: mongo-middleware-cluster-ip-service
            - name: DB_PORT
              value: '27017'
            - name: DATABASE
              value: 'middlewareApiDb'
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'root'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: SENDGRID_API
            - name: REPORT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: report-api
                  key: REPORT_API_KEY
            - name: REPORT_API_URL
              value: http://report-api-cluster-ip-service
            - name: REPORT_API_PORT
              value: '5000'
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET