apiVersion: v1
kind: Service
metadata:
  name: mongo-middleware-node-port
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31000
  selector:
    component: mongo-middleware